import math
print("Введите a,b:")
a=int(input())
b=int(input())
print("Сумма a,b:", a+b)
print("Разница a,b:", a-b)
print("Произведение a,b:",a*b)
print("Частное от деления a,b:", a//b)
print("Остаток от деления a,b:", a%b)
print("Десятичный логарифм числа a:", math.log(a,10))
print("Возведение числа a в степень b", a**b)